typography_spectrum: 0.1397849
color:
  saturation: 0.2329749
  lightness: 0.2724014
  brandStrength: 0.4229391
  rhythmicContrast: 0.9547725
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.4928315
name: Reimagine Business
title: Data Driven
description: Brought to you by @MSBIguy
